// Url:https://leetcode.com/problems/find-the-difference

/*
389. Find the Difference
Easy

Given two strings s and t which consist of only lowercase letters.

String t is generated by random shuffling string s and then add one more letter at a random position.

Find the letter that was added in t.

Example:
Input:
s = "abcd"
t = "abcde"

Output:
e

Explanation:
'e' is the letter that was added.
*/

using System;

namespace InterviewPreperationGuide.Core.LeetCode.problem389 {
    public class Solution {
        public void Init () {
            Console.WriteLine ();
        }

        public char FindTheDifference (string s, string t) {
            return ' ';
        }
    }
}