// Url:https://leetcode.com/problems/find-the-difference

/*
389. Find the Difference
Easy

Given two strings s and t which consist of only lowercase letters.

String t is generated by random shuffling string s and then add one more letter at a random position.

Find the letter that was added in t.

Example:
Input:
s = &quot;abcd&quot;
t = &quot;abcde&quot;

Output:
e

Explanation:
&apos;e&apos; is the letter that was added.
*/

using System;

namespace InterviewPreperationGuide.Core.LeetCode.Solution389
{
    public class Solution
    {
        public void Init() { }

        public char FindTheDifference(string s, string t) { }
    }
}
